import './modules/Popup'
import './modules/SelectC8'

import './modules/BrowserDetection'
import './modules/CheckDevice'
import './modules/LazyLoadImage'

import './modules/FormAnimation'
import './modules/ADA'

import './modules/UserAgent'
import './modules/luxy'
import './modules/Header'
import './modules/Menu'
import './modules/SlideTestimonial'
import './modules/ModInstagramFeed'
import './modules/ModHomepageBanner'
import './modules/ModOverflowContentBlocks'
import './modules/ProductDetail'
import './modules/AnimationScrollPage'
import './modules/ModProductDetailsAccordion'
import './modules/IconGrid'
import './modules/resizeTable'
import './modules/Accordin'
import './modules/CompareProduct'
import './modules/ModContentSlider'
import './modules/ModQuestFeature'
import './modules/VideoSlider'
import './modules/SliderFeature'
import './modules/ImageFeatures'
import './modules/InternalBannerAnimation'
import './modules/Nav'
import './modules/FeatureTab'
import './modules/FeaturedBlogs'
import './modules/FilterBlog'
import './modules/SimilarPosts'
import './modules/StoreLocator'
import './modules/FAQ'
// console.log('App ')
